### ISSUE TITLE
Generalize generation of assets like buildings

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab-server#3]
The code which calls `generate_buildings_with_asset_id` for all buildings which don't have a generated model yet is currently in `assetpos/views/get_assetpositions`. It should be refactored so that this function doesn't have to handle buildings specifically.

I believe a sensible and relatively easy way to solve this would be to generate all assets like this immediately, e.g. directly in the `import_building_footprints` command, since these generated assets need to be further prepared for Godot anyways (`buildings/exported_dae_to_importable_dscn.gd`)

**Comment by kb173** [comment]
This is still very relevant as the building generation process is quite fragile, takes a very long time and is prone to errors (#5). I think that we need to rework the entire process if we want to extend and future-proof it. We should discuss the different possibilities for this (@chrisgraf).

**Comment by chrisgraf** [comment]
as the generation of buildings is open for discussion I will close detailed issues related to the old approach
