### ISSUE TITLE
Buildings should be saved to the resources and be sent with their path

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab-server#4]
Buildings are currently saved in the `buildings` folder. It should be changed so they are saved in the `resources`.

In addition, their assets are currently sent in this format: "Nockberge Testregion_64981"
They should be sent with a correct full path like all other paths instead, e.g. "buildings/importable/Nockberge Testregion_64981.dae.dscn" (or whatever the folder inside the resources will be).

**Comment by kb173** [comment]
Related to #3 - needs to be considered

**Comment by chrisgraf** [comment]
as the generation of buildings is open for discussion I will close detailed issues related to the old approach
